name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.2-beta.6
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.7.0
  rxdart: ^0.28.0

  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  open_filex: ^4.5.0
  sensors_plus: ^3.0.2
  share_plus: ^10.0.2
  collection: ^1.18.0
  url_launcher: ^6.3.0

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: AlicePlugin
      ios:
        pluginClass: AlicePlugin
      macos:
        pluginClass: AlicePlugin
